In [1]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==1.5.0
# !pip install torchvision==0.6.0
# !pip install torchtext==0.3.1
# !pip install numpy==1.21.6
# !pip install matplotlib==3.2.2
# !pip install Pillow==7.1.2
# !pip install opencv-python==4.6.0

# 第9章 torch.nnパッケージ

# 9.3 パラメータの初期値

In [2]:
import torch 
import torchvision
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import torchvision.transforms as transforms
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

## torch.nninit.uniform

In [3]:
w = torch.empty(3, 5)
nn.init.uniform_(w)

tensor([[0.6767, 0.6471, 0.9155, 0.0843, 0.2530],
        [0.0124, 0.0403, 0.9713, 0.7677, 0.7444],
        [0.0739, 0.4056, 0.0561, 0.4145, 0.0939]])

## torch.nn.init.normal

In [4]:
w = torch.empty(3, 5)
nn.init.normal_(w)

tensor([[-0.0099,  0.0719,  1.5106, -0.2540,  0.5408],
        [-1.3753, -0.7779,  1.1082,  1.1179,  0.7643],
        [-0.8206,  0.2930,  0.6857, -0.3989,  0.9966]])

## torch.nn.init.constant


In [5]:
w = torch.empty(3, 5)
nn.init.constant_(w, 0.3)

tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])

## torch.nn.init.eye

In [6]:
w = torch.empty(3, 5)
nn.init.eye_(w)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])

## torch.nn.init.calculate_gain

In [7]:
gain = nn.init.calculate_gain('linear')
print(gain)
gain = nn.init.calculate_gain('conv2d')
print(gain)
gain = nn.init.calculate_gain('relu')
print(gain)
gain = nn.init.calculate_gain('leaky_relu')
print(gain)

1
1
1.4142135623730951
1.4141428569978354


## torch.nn.init.xavier_uniform


In [8]:
w = torch.empty(3, 5)
nn.init.xavier_uniform_(w, gain=nn.init.calculate_gain('relu'))

tensor([[-0.2261,  0.4217,  0.5210,  0.6253, -0.5442],
        [ 0.0381,  0.4265,  0.1117,  0.9086, -0.3756],
        [-0.4110,  1.1312,  0.0986, -0.8452,  0.1126]])

## torch.nn.init.xavier_normal

In [9]:
w = torch.empty(3, 5)
nn.init.xavier_normal_(w)

tensor([[-0.0011,  0.2531, -0.2949,  0.0446,  0.2384],
        [-0.2814, -0.1979, -0.4694, -0.0206, -0.6279],
        [ 0.4138, -0.9194,  0.1177,  1.0447, -0.0902]])

## torch.nn.init.kaiming_uniform

In [10]:
w = torch.empty(3, 5)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')

tensor([[ 1.0593,  0.5936,  0.5774, -0.4797, -1.0354],
        [ 0.6444, -0.1923, -0.9627, -0.4421,  0.3072],
        [-0.1423,  0.2084, -0.9058,  0.3933, -0.1830]])

## torch.nn.init.kaiming_normal

In [11]:
w = torch.empty(3, 5)
nn.init.kaiming_normal_(w, mode='fan_out', nonlinearity='relu')

tensor([[ 0.1833,  1.1950,  0.2702,  0.2567,  1.3099],
        [-0.8622, -0.4217,  0.8484, -1.6390,  1.0361],
        [ 0.5231, -1.2187, -0.0258, -1.9205, -0.4279]])