In [0]:
#colabを使う方はこちらを使用ください。
!pip install torch==0.4.1
!pip install torchvision==0.2.1
!pip install numpy==1.14.6
!pip install matplotlib==2.1.2
!pip install pillow==5.0.0
!pip install opencv-python==3.4.3.18

    100% |████████████████████████████████| 519.5MB 26kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5957c000 @  0x7f18265312a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 2.6MB/s 
    100% |████████████████████████████████| 2.0MB 8.8MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0
    100% |████████████████████████████████| 5.9MB 5.3MB/s 
  Found existing installation: Pillow 5.3.0
    Uninstalling Pillow-5.3.0:
      Successfully uninstalled Pillow-5.3.0


In [0]:
import torch 
import torchvision
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import torchvision.transforms as transforms
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# パラメータの初期値

## 一様分布で初期化する

In [0]:
w = torch.empty(3, 5)
nn.init.uniform_(w)

tensor([[ 0.7945,  0.2324,  0.8830,  0.4259,  0.4476],
        [ 0.7428,  0.4185,  0.4235,  0.2564,  0.2008],
        [ 0.9125,  0.5551,  0.9719,  0.3061,  0.7314]])

## 正規分布で初期化する

In [0]:
w = torch.empty(3, 5)
nn.init.normal_(w)

tensor([[-1.0958, -0.5216,  0.5568,  0.2894,  0.6269],
        [ 0.1691,  2.0882,  0.7058, -2.1592,  1.4674],
        [-0.9148,  0.7325,  0.2636, -0.1951,  0.2942]])

## 指定した値で初期化する


In [0]:
w = torch.empty(3, 5)
nn.init.constant_(w, 0.3)

tensor([[ 0.3000,  0.3000,  0.3000,  0.3000,  0.3000],
        [ 0.3000,  0.3000,  0.3000,  0.3000,  0.3000],
        [ 0.3000,  0.3000,  0.3000,  0.3000,  0.3000]])

## 単位行列で初期化する

In [0]:
w = torch.empty(3, 5)
nn.init.eye_(w)

tensor([[ 1.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.]])

## 与えられた非線形関数の推奨ゲイン値を得る

In [0]:
gain = nn.init.calculate_gain('linear')
print(gain)
gain = nn.init.calculate_gain('conv2d')
print(gain)
gain = nn.init.calculate_gain('relu')
print(gain)
gain = nn.init.calculate_gain('leaky_relu')
print(gain)

1
1
1.4142135623730951
1.4141428569978354


## Glorotの初期値で一様分布の初期化する


In [0]:
w = torch.empty(3, 5)
nn.init.xavier_uniform_(w, gain=nn.init.calculate_gain('relu'))

tensor([[-0.0221,  0.4529, -1.0402,  0.9492, -1.0725],
        [-0.9870, -1.0100, -0.3421,  0.9241,  0.6219],
        [-1.1718, -1.2070,  0.7530,  0.8157,  0.9457]])

## Glorotの初期値で正規分布の初期化する

In [0]:
w = torch.empty(3, 5)
nn.init.xavier_normal_(w)

tensor([[-0.0776,  0.1208, -0.2579, -0.3210, -0.3336],
        [-0.3571, -0.1586, -0.8465,  0.2294,  0.6384],
        [-0.4535, -0.8314,  0.4807, -0.5215,  0.2322]])

## Heの初期値で一様分布の初期化をする

In [0]:
w = torch.empty(3, 5)
nn.init.kaiming_uniform_(w, mode='fan_in', nonlinearity='relu')

tensor([[-0.6863,  0.0687,  0.5840,  0.6194,  0.6268],
        [-0.5025, -0.2338,  0.2653,  0.4436, -0.6380],
        [-0.9431,  0.2097,  0.3742, -0.7311,  0.5842]])

## Heの初期値で正規分布の初期化をする

In [0]:
w = torch.empty(3, 5)
nn.init.kaiming_normal_(w, mode='fan_out', nonlinearity='relu')

tensor([[ 0.4191,  0.7646, -0.1674, -1.4745, -0.3846],
        [-1.2578,  0.5891, -0.1393, -0.0649,  1.0568],
        [-0.3875,  0.0445,  0.4014,  0.4188,  0.5702]])