In [1]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==0.4.1
# !pip install torchvision==0.2.1
# !pip install numpy==1.14.6
# !pip install matplotlib==2.1.2
# !pip install pillow==5.0.0
# !pip install opencv-python==3.4.3.18

# 第8章 torchパッケージ

# 8.4 数学演算

In [2]:
import torch
import numpy as np

## torch.abs


In [3]:
#要素単位の絶対値を計算する
x = torch.abs(torch.tensor([-1, -2, 3]))
x

tensor([1, 2, 3])

## torch.add


In [4]:
#要素単位でスカラー値を加算する
x = torch.randn(4)
x

tensor([ 0.0283,  0.2047,  0.4239, -1.2039])

In [5]:
x = torch.add(x, 20)
x

tensor([20.0283, 20.2047, 20.4239, 18.7961])

## torch.clamp


In [6]:
#Tensorの値を指定範囲に収める
x = torch.randn(4)
x

tensor([-0.4512, -0.8345,  0.7358,  0.0897])

In [7]:
torch.clamp(x, min=-0.5, max=0.5)

tensor([-0.4512, -0.5000,  0.5000,  0.0897])

In [8]:
x = torch.randn(4)
x

tensor([-0.8135,  1.3825, -0.9884,  0.9450])

In [9]:
x = torch.clamp(x, max=0.5)
x

tensor([-0.8135,  0.5000, -0.9884,  0.5000])

## torch.div

In [10]:
x = torch.randn(5)
x

tensor([-0.9048, -1.4121,  1.0968, -1.0365,  0.4437])

In [13]:
#入力の各要素をスカラー値で除算する
torch.div(x, 0.5)

tensor([-1.8096, -2.8242,  2.1935, -2.0731,  0.8873])

In [14]:
x1 = torch.randn(4, 4)
x1

tensor([[-1.1615, -0.9150, -0.1294, -1.0382],
        [ 0.2021,  0.6492,  2.3038,  0.0206],
        [-0.5287, -0.5786, -1.2618, -0.5698],
        [-0.3052, -0.0076,  0.2109, -0.6430]])

In [15]:
x2 = torch.randn(4)
x2

tensor([-0.0441, -0.9764,  1.2555,  1.3311])

In [16]:
torch.div(x1, x2)

tensor([[26.3567,  0.9371, -0.1031, -0.7800],
        [-4.5856, -0.6649,  1.8350,  0.0155],
        [11.9971,  0.5926, -1.0050, -0.4281],
        [ 6.9249,  0.0077,  0.1679, -0.4831]])

## torch.exp


In [17]:
import math
#入力の要素に指数関数を計算する
torch.exp(torch.tensor([0, math.log(2)]))

tensor([1., 2.])

## torch.log


In [19]:
#自然対数を計算する
torch.log(torch.randn(5))

tensor([    nan,  0.5703,     nan,     nan, -1.0346])

## torch.mul


In [20]:
x = torch.randn(3)
x

tensor([ 0.5819, -0.7323,  0.1493])

In [21]:
#各要素で乗算する
torch.mul(x, 100)

tensor([ 58.1945, -73.2279,  14.9286])

In [22]:
x1 = torch.randn(4, 1)
x1

tensor([[ 0.2841],
        [ 1.0856],
        [ 0.9962],
        [-1.2155]])

In [23]:
x2 = torch.randn(1, 4)
x2

tensor([[-0.4404,  2.0857,  0.8820,  0.7800]])

In [24]:
torch.mul(x1, x2)

tensor([[-0.1251,  0.5925,  0.2505,  0.2216],
        [-0.4781,  2.2642,  0.9575,  0.8468],
        [-0.4387,  2.0778,  0.8786,  0.7771],
        [ 0.5353, -2.5352, -1.0720, -0.9481]])

## torch.round


In [25]:
x = torch.randn(4)
x

tensor([-1.6679, -1.0692, -1.8575,  2.0475])

In [27]:
#最も近い整数に丸める
torch.round(x)

tensor([-2., -1., -2.,  2.])

## torch.sigmoid


In [28]:
x = torch.randn(4)
x

tensor([0.6733, 0.0848, 0.3042, 0.4951])

In [30]:
#sigmoidを計算する
torch.sigmoid(x)

tensor([0.6622, 0.5212, 0.5755, 0.6213])

## torch.sign


In [31]:
x = torch.randn(4)
x

tensor([-0.5907, -2.0679,  1.2866, -0.1449])

In [32]:
#符号を得る
torch.sign(x)

tensor([-1., -1.,  1., -1.])

## torch.sqrt


In [33]:
x = torch.randn(4)
x

tensor([-0.0669,  1.2277,  0.8040, -0.7706])

In [34]:
#平方根を計算する
torch.sqrt(x)

tensor([   nan, 1.1080, 0.8967,    nan])

## torch.tanh


In [35]:
x = torch.randn(4)
x

tensor([-0.1610, -2.0673, -0.3615, -0.3383])

In [37]:
#tanhを計算する
torch.tanh(x)

tensor([-0.1596, -0.9685, -0.3465, -0.3260])

## torch.bmm


In [38]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
#バッチを含んだTensor同士の行列積を計算する
res = torch.bmm(batch1, batch2)
res.size()

torch.Size([10, 3, 5])

## torch.dot



In [40]:
#１階Tensor同士の内積を計算する
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

tensor(7)

## torch.mm


In [41]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
#行列Tensor同士の行列積を計算する
torch.mm(mat1, mat2)

tensor([[-2.1211, -1.7908, -0.4957],
        [ 1.1801,  0.5357, -0.4434]])

## torch.matmul


In [42]:
# ベクトル x ベクトル
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
#色々なTensor同士の行列積を計算する
torch.matmul(tensor1, tensor2).size()

torch.Size([])

In [43]:
# 行列 x ベクトル
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([3])

In [44]:
# バッチ行列 x ブロードキャストされたベクトル
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3])

In [45]:
# バッチ行列 x バッチ行列
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])

In [46]:
#バッチ処理された行列 x ブロードキャストされた行列
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

torch.Size([10, 3, 5])