In [1]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==1.5.0
# !pip install torchvision==0.6.0
# !pip install torchtext==0.3.1
# !pip install numpy==1.21.6
# !pip install matplotlib==3.2.2
# !pip install Pillow==7.1.2
# !pip install opencv-python==4.6.0

# 第8章 torchパッケージ

# 8.2 インデックス、スライシング、結合によるTensorの作成



In [8]:
import torch
import numpy as np

## torch.cat


In [9]:
#指定された次元の指定されたシーケンスTensor同士を連結する
x = torch.randn(2, 3)
x

tensor([[-0.8634,  0.2428, -0.0898],
        [ 0.2704, -0.7322,  0.5783]])

In [10]:
torch.cat((x, x, x), 0)

tensor([[-0.8634,  0.2428, -0.0898],
        [ 0.2704, -0.7322,  0.5783],
        [-0.8634,  0.2428, -0.0898],
        [ 0.2704, -0.7322,  0.5783],
        [-0.8634,  0.2428, -0.0898],
        [ 0.2704, -0.7322,  0.5783]])

In [11]:
torch.cat((x, x, x), 1)

tensor([[-0.8634,  0.2428, -0.0898, -0.8634,  0.2428, -0.0898, -0.8634,  0.2428,
         -0.0898],
        [ 0.2704, -0.7322,  0.5783,  0.2704, -0.7322,  0.5783,  0.2704, -0.7322,
          0.5783]])

## torch.index_select

In [12]:
#インデックスを指定して既存のTensorからTensorを切り出す
x = torch.randn(3, 4)
x

tensor([[-0.7763, -2.1231,  0.1880,  1.1897],
        [ 0.9949,  1.7188, -0.1519, -0.2163],
        [ 0.4957, -0.2690, -0.8190,  1.1134]])

In [13]:
x[1]

tensor([ 0.9949,  1.7188, -0.1519, -0.2163])

In [14]:
x[:,0]

tensor([-0.7763,  0.9949,  0.4957])

In [15]:
indices = torch.tensor([0, 2])
torch.index_select(x, 0, indices)

tensor([[-0.7763, -2.1231,  0.1880,  1.1897],
        [ 0.4957, -0.2690, -0.8190,  1.1134]])

In [16]:
torch.index_select(x, 1, indices)

tensor([[-0.7763,  0.1880],
        [ 0.9949, -0.1519],
        [ 0.4957, -0.8190]])

## torch.squeeze


In [17]:
#大きさが１の次元を削除したTensorを作成する
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [18]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [19]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [20]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [21]:
y = torch.squeeze(x, 3)
y.size()

torch.Size([2, 1, 2, 2])

## torch.t

In [22]:
#Tensorを転置する
x = torch.randn(2, 3)
x

tensor([[1.0512, 0.8211, 0.4865],
        [0.0487, 0.7302, 0.5427]])

In [23]:
torch.t(x)

tensor([[1.0512, 0.0487],
        [0.8211, 0.7302],
        [0.4865, 0.5427]])

## torch.transpose


In [24]:
#Tensorの次元を入れ替える
x = torch.randn(2, 3)
x

tensor([[-0.5909,  0.5229, -0.9337],
        [ 0.9394,  1.7050, -0.8571]])

In [25]:
torch.transpose(x, 0, 1)

tensor([[-0.5909,  0.9394],
        [ 0.5229,  1.7050],
        [-0.9337, -0.8571]])

## torch.unsqueeze


In [26]:
#指定された位置にサイズ1の次元を挿入する
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [27]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])