In [1]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==1.5.0
# !pip install torchvision==0.6.0
# !pip install torchtext==0.3.1
# !pip install numpy==1.21.6
# !pip install matplotlib==3.2.2
# !pip install Pillow==7.1.2
# !pip install opencv-python==4.6.0

# 第8章 torchパッケージ

# 8.3 ランダムサンプリング

In [5]:
import torch
import numpy as np

## torch.bernoulli

In [6]:
x = torch.empty(3, 3).uniform_(0, 1)
x

tensor([[0.0077, 0.4595, 0.2962],
        [0.7911, 0.9954, 0.4942],
        [0.9579, 0.0604, 0.2557]])

In [7]:
torch.bernoulli(x)

tensor([[0., 0., 0.],
        [1., 1., 1.],
        [1., 0., 0.]])

In [8]:
x = torch.ones(3, 3) 
torch.bernoulli(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x = torch.zeros(3, 3)
torch.bernoulli(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## torch.multinomial


In [10]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float)
torch.multinomial(weights, 4)

tensor([2, 1, 0, 0])

In [11]:
torch.multinomial(weights, 4, replacement=True)

tensor([1, 1, 1, 1])

## torch.normal


In [15]:
#このコードは環境によってはtorch.LongTensorのエラーがでる
# torch.normal(mean=torch.arange(1, 11), std=torch.arange(1, 0, -0.1))
torch.normal(mean=torch.arange(1, 11).float(), std=torch.arange(1, 0, -0.1))

tensor([1.6513, 3.4453, 2.8962, 3.8900, 5.1079, 6.3268, 6.7915, 7.6993, 9.3702,
        9.8486])

In [16]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

tensor([ 1.3913, -0.1603, -1.8675, -7.2500, -0.2315])

In [17]:
torch.normal(mean=torch.arange(1., 6.))

tensor([0.9454, 3.3691, 3.5314, 3.1417, 6.9405])

## torch.rand

In [18]:
torch.rand(4)

tensor([0.3264, 0.6990, 0.5973, 0.4938])

In [19]:
torch.rand(2, 3)

tensor([[0.2095, 0.4693, 0.0006],
        [0.9062, 0.2943, 0.9798]])

## torch.randn

In [20]:
torch.randn(4)

tensor([-0.7528,  0.9386,  1.0346,  0.8403])

In [21]:
torch.randn(2, 3)

tensor([[1.0240, 0.6602, 0.8816],
        [1.2194, 0.1368, 0.2297]])

## torch.randperm

In [22]:
torch.randperm(4)

tensor([1, 0, 2, 3])