In [0]:
#colabを使う方はこちらを使用ください。
!pip install torch==0.4.1
!pip install torchvision==0.2.1
!pip install numpy==1.14.6
!pip install matplotlib==2.1.2
!pip install pillow==5.0.0
!pip install opencv-python==3.4.3.18

    100% |████████████████████████████████| 519.5MB 25kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5983e000 @  0x7f0f0a30f2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 2.3MB/s 
    100% |████████████████████████████████| 2.0MB 12.0MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0
    100% |████████████████████████████████| 5.9MB 6.6MB/s 
  Found existing installation: Pillow 5.3.0
    Uninstalling Pillow-5.3.0:
      Successfully uninstalled Pillow-5.3.0


In [0]:
import torch
import numpy as np

# torchパッケージ

# 数学演算

## 要素単位の絶対値を計算する



In [0]:
x = torch.abs(torch.tensor([-1, -2, 3]))
x

## 要素単位でスカラー値を加算する


In [0]:
x = torch.randn(4)
x

In [0]:
x = torch.add(x, 20)
x

## Tensorの値を指定範囲に収める


In [0]:
x = torch.randn(4)
x

In [0]:
torch.clamp(x, min=-0.5, max=0.5)

In [0]:
x = torch.randn(4)
x

In [0]:
x = torch.clamp(x, max=0.5)
x

## 入力の各要素をスカラー値で除算する


In [3]:
x = torch.randn(5)
x

tensor([-0.2873, -0.7349,  0.8945, -0.2045,  0.1864])

In [4]:
torch.div(x, 0.5)

tensor([-0.5746, -1.4699,  1.7890, -0.4090,  0.3728])

In [5]:
x1 = torch.randn(4, 4)
x1

tensor([[-0.8312,  0.0298,  1.6882, -0.6514],
        [ 0.1920, -0.7320, -0.6747, -1.1542],
        [ 0.2711,  1.0600, -1.4565,  1.8304],
        [-1.5805, -0.6478, -1.2485,  0.9841]])

In [6]:
x2 = torch.randn(4)
x2

tensor([-1.3214, -0.1239,  0.9129,  0.4363])

In [7]:
torch.div(x1, x2)

tensor([[ 0.6290, -0.2403,  1.8492, -1.4931],
        [-0.1453,  5.9076, -0.7390, -2.6457],
        [-0.2052, -8.5549, -1.5954,  4.1958],
        [ 1.1960,  5.2286, -1.3676,  2.2558]])

## 入力の要素に指数関数を計算する


In [0]:
import math
torch.exp(torch.tensor([0, math.log(2)]))

## 自然対数を計算する


In [0]:
torch.log(torch.randn(5))

## 各要素で乗算する


In [0]:
x = torch.randn(3)
x

In [0]:
torch.mul(x, 100)

In [0]:
x1 = torch.randn(4, 1)
x1

In [0]:
x2 = torch.randn(1, 4)
x2

In [0]:
torch.mul(x1, x2)

## 最も近い整数に丸める


In [0]:
x = torch.randn(4)
x

In [0]:
torch.round(x)

## sigmoidを計算する



In [0]:
x = torch.randn(4)
x

In [0]:
torch.sigmoid(x)

## 符号を得る



In [0]:
x = torch.randn(4)
x

In [0]:
torch.sign(x)

## 平方根を計算する



In [0]:
x = torch.randn(4)
x

In [0]:
torch.sqrt(x)

## tanhを計算する


In [0]:
x = torch.randn(4)
x

In [0]:
torch.tanh(x)

## バッチを含んだTensor同士の行列積を計算する



In [0]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
res.size()

## １階Tensor同士の内積を計算する




In [0]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

## 行列Tensor同士の行列積を計算する



In [0]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)

## 色々なTensor同士の行列積を計算する



In [0]:
# ベクトル x ベクトル
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()

In [0]:
# 行列 x ベクトル
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

In [0]:
# バッチ行列 x ブロードキャストされたベクトル
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

In [0]:
# バッチ行列 x バッチ行列
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

In [0]:
#バッチ処理された行列 x ブロードキャストされた行列
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()