In [2]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==0.4.1
# !pip install torchvision==0.2.1
# !pip install numpy==1.14.6
# !pip install matplotlib==2.1.2
# !pip install pillow==5.0.0
# !pip install opencv-python==3.4.3.18

# 第8章 torchパッケージ

# 8.1 Tensorの生成

In [3]:
import torch
import numpy as np

## torch.tensor





In [4]:
#リストやndarrayからTensorを作成する
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                 dtype=torch.float64,
                 device=torch.device('cuda:0'))

tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64)

In [6]:
torch.tensor([0, 1])  # データの型推論

tensor([0, 1])

In [7]:
#スカラー
torch.tensor(3.14159)

tensor(3.1416)

In [8]:
#空のテンソルを作成
torch.tensor([])

tensor([])

## torch.from_numpy




In [9]:
#numpy.ndarrayからTensorを作成する
x = np.array([1, 2, 3])
t = torch.from_numpy(x)
t

tensor([1, 2, 3])

In [10]:
t[0] = -1
x

array([-1,  2,  3])

## torch.zeros

In [11]:
#形状を指定して値が全て0のTensorを作成する
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## torch.zeros_like

In [12]:
#入力と同じ形状で値が全て0のTensorを作成する
input = torch.empty(2, 3)
input

tensor([[-48590909368567118171302082144894976.0000,
                                            0.0000,
         -48590909368567118171302082144894976.0000],
        [                                   0.0000,
                                            0.0000,
                                            0.0000]])

In [13]:
torch.zeros_like(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

## torch.eye

In [14]:
#単位行列のTensorを作成する
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [15]:
n_class = 3
label = 0
eye = torch.eye(n_class)
print(eye)
onehot_label = eye[label].view(-1, n_class)
print(onehot_label)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.]])


## torch.set_default_dtype


In [16]:
#Tensor作成時の標準のデータ型を設定する
torch.tensor([1.2, 3]).dtype

torch.float32

In [17]:
torch.set_default_dtype(torch.float64)
torch.tensor([1.2, 3]).dtype

torch.float64

## torch.numel


In [18]:
#入力Tensor内の要素の総数を取得する
x = torch.randn(1, 2, 3, 1)
torch.numel(x)

6

In [19]:
x = torch.zeros(4,4)
torch.numel(x)

16

## torch.is_tensor


In [20]:
#Tensor型か確認する
x = torch.Tensor(5, 3)
torch.is_tensor(x)

True