In [0]:
#colabを使う方はこちらを使用ください。
!pip install torch==0.4.1
!pip install torchvision==0.2.1
!pip install numpy==1.14.6
!pip install matplotlib==2.1.2
!pip install pillow==5.0.0
!pip install opencv-python==3.4.3.18

    100% |████████████████████████████████| 519.5MB 25kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5983e000 @  0x7f0f0a30f2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 2.3MB/s 
    100% |████████████████████████████████| 2.0MB 12.0MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0
    100% |████████████████████████████████| 5.9MB 6.6MB/s 
  Found existing installation: Pillow 5.3.0
    Uninstalling Pillow-5.3.0:
      Successfully uninstalled Pillow-5.3.0


In [0]:
import torch
import numpy as np

# torchパッケージ

# Tensor

## リストやndarrayからTensorを作成する





In [0]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [0]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                 dtype=torch.float64,
                 device=torch.device('cuda:0'))

tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64)

In [0]:
torch.tensor([0, 1])  # データの型推論

tensor([0, 1])

In [0]:
#スカラー
torch.tensor(3.14159)

tensor(3.1416)

In [0]:
#空のテンソルを作成
torch.tensor([])

tensor([])

## Tensor型か確認する



In [0]:
x = torch.Tensor(5, 3)
torch.is_tensor(x)

## numpy.ndarrayからTensorを作成する




In [0]:
x = np.array([1, 2, 3])
t = torch.from_numpy(x)
t

In [0]:
t[0] = -1
x

## 形状を指定して値が全て0のTensorを作成する


In [0]:
torch.zeros(2, 3)

## 入力と同じ形状で値が全て0のTensorを作成する


In [0]:
input = torch.empty(2, 3)
input

In [0]:
torch.zeros_like(input)

## 単位行列のTensorを作成する

In [0]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
n_class = 3
label = 0
eye = torch.eye(n_class)
print(eye)
onehot_label = eye[label].view(-1, n_class)
print(onehot_label)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1., 0., 0.]])


## Tensor作成時の標準のデータ型を設定する


In [0]:
torch.tensor([1.2, 3]).dtype

In [0]:
torch.set_default_dtype(torch.float64)
torch.tensor([1.2, 3]).dtype

## 入力Tensor内の要素の総数を取得する



In [0]:
x = torch.randn(1, 2, 3, 1)
torch.numel(x)

In [0]:
x = torch.zeros(4,4)
torch.numel(x)