https://pytorch.org/docs/stable/torch.html

In [1]:
!pip install torchvision==0.2.1
!pip install torch==0.4.1
!pip install pillow==4.2.0

    100% |████████████████████████████████| 61kB 2.3MB/s 
    100% |████████████████████████████████| 519.5MB 30kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x5a4c4000 @  0x7fa6baddb2a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 2.0MB 5.5MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0
    100% |████████████████████████████████| 5.8MB 5.9MB/s 
  Found existing installation: Pillow 5.3.0
    Uninstalling Pillow-5.3.0:
      Successfully uninstalled Pillow-5.3.0


# 第1章　torchパッケージ

# テンソル

In [0]:
import torch
import numpy as np

## データでテンソルを作成する





In [3]:
torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [4]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                 dtype=torch.float64,
                 device=torch.device('cuda:0'))

tensor([[0.1111, 0.2222, 0.3333]], device='cuda:0', dtype=torch.float64)

In [5]:
torch.tensor([0, 1])  # データの型推論

tensor([0, 1])

In [6]:
#スカラー
torch.tensor(3.14159)

tensor(3.1416)

In [7]:
#空のテンソルを作成
torch.tensor([])

tensor([])

## テンソル型かを確認する



In [0]:
x = torch.Tensor(5, 3)
torch.is_tensor(x)

## numpy.ndarrayからテンソルを作成する




In [0]:
x = np.array([1, 2, 3])
t = torch.from_numpy(x)
t

In [0]:
t[0] = -1
x

## スカラー値0の指定した形状のテンソルを作成する


In [0]:
torch.zeros(2, 3)

In [0]:
torch.zeros(5)

## 入力と同じ形状のスカラー値0のテンソルを作成する


In [0]:
input = torch.empty(2, 3)
input

In [0]:
torch.zeros_like(input)

## 単位行列のテンソルを作成する

In [3]:
x = torch.eye(3)
x

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

## テンソルの初期の型を設定する


In [0]:
torch.tensor([1.2, 3]).dtype

In [0]:
torch.set_default_dtype(torch.float64)
torch.tensor([1.2, 3]).dtype

## 入力テンソル内の要素の総数を取得する



In [0]:
x = torch.randn(1, 2, 3, 1)
torch.numel(x)

In [0]:
x = torch.zeros(4,4)
torch.numel(x)

# インデックス、スライシング、結合



## 指定された次元の指定されたシーケンステンソル同士を連結する

  


In [0]:
x = torch.randn(2, 3)
x

In [0]:
torch.cat((x, x, x), 0)

In [0]:
torch.cat((x, x, x), 1)

## インデックスを指定して任意のテンソルを返すには


In [0]:
x = torch.randn(3, 4)
x

In [0]:
x[1]

In [0]:
x[:,0]

In [0]:
indices = torch.tensor([0, 2])
torch.index_select(x, 0, indices)

In [0]:
torch.index_select(x, 1, indices)

## サイズ1の入力のすべての次元が削除されたテンソルを返す


In [0]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

In [0]:
y = torch.squeeze(x)
y.size()

In [0]:
y = torch.squeeze(x, 0)
y.size()

In [0]:
y = torch.squeeze(x, 1)
y.size()

In [0]:
y = torch.squeeze(x, 3)
y.size()

## テンソルを転置する


In [0]:
x = torch.randn(2, 3)
x

In [0]:
torch.t(x)

## テンソルの次元を入れ替える



In [0]:
x = torch.randn(2, 3)
x

In [0]:
torch.transpose(x, 0, 1)

## 指定された位置にサイズ1の次元を挿入するには



In [0]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

In [0]:
torch.unsqueeze(x, 1)

# ランダムサンプリング

## Bernoulli分布からのバイナリ乱数（0または1）を生成する


In [0]:
x = torch.empty(3, 3).uniform_(0, 1) # generate a uniform random matrix with range [0, 1]
x

In [0]:
torch.bernoulli(x)

In [0]:
x = torch.ones(3, 3) # probability of drawing "1" is 1
torch.bernoulli(x)

In [0]:
x = torch.zeros(3, 3) # probability of drawing "1" is 0
torch.bernoulli(x)

## 多項分布からサンプリングされたテンソルを生成する


In [0]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float) # create a tensor of weights
torch.multinomial(weights, 4)

In [0]:
torch.multinomial(weights, 4, replacement=True)

## 正規分布からサンプリングされたテンソルを生成する



In [0]:
torch.normal(mean=torch.arange(1, 11), std=torch.arange(1, 0, -0.1))

In [0]:
torch.normal(mean=0.5, std=torch.arange(1., 6.))

In [0]:
torch.normal(mean=torch.arange(1., 6.))

## 区間[0,1]上の一様分布から乱数で満たされたテンソルを生成する
    




In [0]:
torch.rand(4)

In [0]:
torch.rand(2, 3)

## 標準正規分布からの乱数で満たされたテンソルを作成する


In [0]:
torch.randn(4)

In [0]:
torch.randn(2, 3)

## 0からn-1までの整数のランダム並び替えする


In [0]:
torch.randperm(4)

# オブジェクトの保存と読み込み

## オブジェクトをディスクファイルに保存


In [0]:
import io
# Save to file
x = torch.tensor([0, 1, 2, 3, 4])
torch.save(x, 'tensor.pt')

In [0]:
!ls

In [0]:
# Save to io.BytesIO buffer
buffer = io.BytesIO()
torch.save(x, buffer)

## torch.save()で保存されたオブジェクトを読み込む


```
torch.load(f, map_location=None, pickle_module=<module 'pickle' from '/private/home/soumith/anaconda3/lib/python3.6/pickle.py'>)
```

f：ファイルライクなオブジェクト、またはファイル名を含む文字列    
map_location：関数、torch.device、文字列、または格納場所を再マップする方法を指定するdict    
pickle_module：メタデータとオブジェクトのunpickleに使用されるモジュール    

In [0]:
torch.load('tensors.pt')
# Load all tensors onto the CPU
torch.load('tensors.pt', map_location='cpu')
# Load all tensors onto the CPU, using a function
torch.load('tensors.pt', map_location=lambda storage, loc: storage)
# Load all tensors onto GPU 1
torch.load('tensors.pt', map_location=lambda storage, loc: storage.cuda(1))
# Map tensors from GPU 1 to GPU 0
torch.load('tensors.pt', map_location={'cuda:1':'cuda:0'})
# Load tensor from io.BytesIO object
with open('tensor.pt') as f:
        buffer = io.BytesIO(f.read())
torch.load(buffer)

# 並列処理


## CPU操作の並列化に使用されるOpenMPスレッドの数を取得します。

# 勾配計算を局所的に無効にする

Locally disabling gradient computation

# 数学演算

## 要素単位の絶対値を計算したテンソルを得る



In [0]:
x = torch.abs(torch.tensor([-1, -2, 3]))
x

## 要素単位でスカラー値を加算したテンソルを得るには


In [0]:
x = torch.randn(4)
x

In [0]:
x = torch.add(x, 20)
x

## 入力の全要素をminとmaxで固定したテンソルを得る


In [0]:
x = torch.randn(4)
x

In [0]:
torch.clamp(x, min=-0.5, max=0.5)

In [0]:
x = torch.randn(4)
x

In [0]:
x = torch.clamp(x, max=0.5)
x

## 入力の各要素をスカラー値で除算したテンソルを作成する


In [4]:
x = torch.randn(5)
x

tensor([-0.9870,  0.0638,  0.0935, -0.2603,  0.1708])

In [5]:
torch.div(x, 0.5)

tensor([-1.9739,  0.1275,  0.1870, -0.5206,  0.3415])

In [6]:
x1 = torch.randn(4, 4)
x1

tensor([[ 0.6301,  0.3588, -0.1099, -0.4234],
        [-0.4427, -0.0435,  0.1775,  1.2960],
        [-0.4093,  0.6002,  0.4328, -0.1677],
        [-2.4244,  1.0269, -1.5184,  2.4926]])

In [7]:
x2 = torch.randn(4)
x2

tensor([ 0.3686,  0.9814, -0.4457,  1.0450])

In [8]:
torch.div(x1, x2)

tensor([[ 1.7097,  0.3656,  0.2466, -0.4052],
        [-1.2012, -0.0444, -0.3983,  1.2402],
        [-1.1105,  0.6116, -0.9711, -0.1605],
        [-6.5777,  1.0463,  3.4066,  2.3853]])

In [10]:
torch.div(0.0, 0.5)

TypeError: ignored

In [11]:
torch.div(0.1, 0.0)

TypeError: ignored

## 入力の要素に指数関数を適応したテンソルを作成する


In [0]:
import math
torch.exp(torch.tensor([0, math.log(2)]))

## 自然対数を適応したテンソルを作成する


In [0]:
torch.log(torch.randn(5))

## スカラー値入力を各要素で乗算したテンソルを得る


In [0]:
x = torch.randn(3)
x

In [0]:
torch.mul(x, 100)

## テンソル入力の各要素で他のテンソルと乗算したテンソルを得る



In [0]:
x1 = torch.randn(4, 1)
x1

In [0]:
x2 = torch.randn(1, 4)
x2

In [0]:
torch.mul(x1, x2)

## 最も近い整数に丸めたテンソルを作成する



In [0]:
x = torch.randn(4)
x

In [0]:
torch.pow(x, 2)

In [0]:
exp = torch.arange(1, 5)
exp

In [0]:
x = torch.arange(1, 5)
x

## 最も近い整数に丸めたテンソルを作成する


In [0]:
x = torch.randn(4)
x

In [0]:
torch.round(x)

## シグモイドを適応したテンソルを作成する



In [0]:
x = torch.randn(4)
x

In [0]:
torch.sigmoid(x)

## 符号を変更したテンソルを作成する



In [0]:
x = torch.randn(4)
x

In [0]:
torch.sign(x)

## 平方根を適応したテンソルを作成する



In [0]:
x = torch.randn(4)
x

In [0]:
torch.sqrt(x)

## tanhを適応したテンソルを作成する


In [0]:
x = torch.randn(4)
x

In [0]:
torch.tanh(x)

## 入力ベクトルが対角である正方行列を適応したテンソルを作成する


In [0]:
x = torch.randn(3)
x

In [0]:
torch.diag(x)

In [0]:
torch.diag(x, 1)

## batch1とbatch2に格納された行列のバッチ行列の行列積を得る



In [0]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
res.size()

## 2つのテンソルの内積を得る




In [0]:
torch.dot(torch.tensor([2, 3]), torch.tensor([2, 1]))

## 2つのテンソルの行列積を得る



In [0]:
# ベクトル x ベクトル
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)
torch.matmul(tensor1, tensor2).size()

In [0]:
# 行列 x ベクトル
tensor1 = torch.randn(3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

In [0]:
# バッチ行列 x ブロードキャストされたベクトル
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4)
torch.matmul(tensor1, tensor2).size()

In [0]:
# バッチ行列 x バッチ行列
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(10, 4, 5)
torch.matmul(tensor1, tensor2).size()

In [0]:
#バッチ処理された行列 x ブロードキャストされた行列
tensor1 = torch.randn(10, 3, 4)
tensor2 = torch.randn(4, 5)
torch.matmul(tensor1, tensor2).size()

## 行列mat1とmat2の行列乗算の結果を得る



In [0]:
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.mm(mat1, mat2)