In [1]:
# #colabを使う方はこちらを使用ください。
# !pip install torch==0.4.1
# !pip install torchvision==0.2.1

    100% |████████████████████████████████| 519.5MB 27kB/s 
tcmalloc: large alloc 1073750016 bytes == 0x59e1c000 @  0x7f21655d02a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070
    100% |████████████████████████████████| 61kB 5.2MB/s 
    100% |████████████████████████████████| 2.0MB 13.3MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


In [2]:
import torch
torch.__version__

'0.4.1'

In [0]:
import torch
import torchvision
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torchvision.transforms as transforms
%matplotlib inline
from matplotlib import pyplot as plt

# テンソル


## テンソルの変換

In [4]:
np_array = np.array([0, 1, 2, 3])
np_array

array([0, 1, 2, 3])

In [5]:
torch_array = torch.from_numpy(np_array)
torch_array

tensor([0, 1, 2, 3])

In [7]:
torch2np_array = torch_array.numpy()
torch2np_array

array([0, 1, 2, 3])

In [19]:
np_array = np.array([[0, 1, 2], [3, 4, 5]])
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch_array

tensor([[0, 1, 2],
        [3, 4, 5]])

In [21]:
np_array = np.array([[[1], [2]], [[3], [4]]])
torch_array = torch.from_numpy(np_array)
torch2np_array = torch_array.numpy()
torch_array

tensor([[[1],
         [2]],

        [[3],
         [4]]])

## 色々なテンソルの作成

In [4]:
np_array = np.arange(10)
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
torch_array = torch.arange(10)
torch_array

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np_array = np.linspace(0, 1, 6)
np_array

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [7]:
torch_array = torch.linspace(0, 1, 6)
torch_array

tensor([0.0000, 0.2000, 0.4000, 0.6000, 0.8000, 1.0000])

In [8]:
np_array = np.ones((3, 3))
np_array

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
torch_array = torch.ones((3, 3))
torch_array

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
np_array = np.zeros((2, 2))
np_array

array([[0., 0.],
       [0., 0.]])

In [7]:
torch_array = torch.zeros((2, 2))
torch_array

tensor([[0., 0.],
        [0., 0.]])

In [12]:
np_array = np.random.randn(4)
np_array

array([ 0.23279165, -1.62465575,  1.96698637,  0.01175967])

In [13]:
torch_array = torch.randn(4)
torch_array

array([-0.17320862,  0.01417954,  0.33963354, -0.69648168])

## テンソルの操作

In [26]:
#形状変換
torch_array = torch.arange(10)
print(torch_array)
torch_array = torch_array.view(5, 2)
print(torch_array)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [32]:
#軸入れ替え
torch_array = torch.arange(10)
torch_array = torch_array.view(5, 2)
print(torch_array)
torch_array = torch_array.transpose(0, 1)
print(torch_array)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 2, 4, 6, 8],
        [1, 3, 5, 7, 9]])


In [30]:
#インデックス指定
torch_array = torch.arange(10)
torch_array[2]

tensor(2)

In [29]:
#スライス
torch_array = torch.arange(10)
torch_array[2:5]

tensor([2, 3, 4])

In [55]:
#要素単位の加算
x1 = torch.arange(4)
print(torch.add(x1, 4))

#要素単位の乗算
x1 = torch.arange(4)
print(torch.mul(x1, 4))

tensor([4, 5, 6, 7])
tensor([ 0,  4,  8, 12])


In [56]:
#ベクトル同士の内積
x1 = torch.arange(4)
x2 = torch.arange(4)
print(torch.matmul(x1, x2))
print(torch.dot(x1, x2))

#行列とベクトルの積
X1 = torch.arange(8).view(2, 4)
x2 = torch.arange(4)
print(torch.matmul(X1, x2))
print(torch.mv(X1, x2))

#行列同士の積
X1 = torch.arange(8).view(2, 4)
X2 = torch.arange(8).view(2, 4).t()
print(torch.matmul(X1, X2))
print(torch.mm(X1, X2))

tensor(14)
tensor(14)
tensor([14, 38])
tensor([14, 38])
tensor([[ 14,  38],
        [ 38, 126]])
tensor([[ 14,  38],
        [ 38, 126]])


In [54]:
#バッチサイズ3の(2,4)行列と(4,2)行列の行列積 
X1 = torch.arange(24).view(-1, 2, 4)
X2 = torch.arange(24).view(-1, 4, 2)
print(X1.size())
print(X2.size())
print(torch.matmul(X1, X2))
print(torch.bmm(X1, X2))

torch.Size([3, 2, 4])
torch.Size([3, 4, 2])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])
tensor([[[  28,   34],
         [  76,   98]],

        [[ 428,  466],
         [ 604,  658]],

        [[1340, 1410],
         [1644, 1730]]])


## データ型

In [11]:
np_array = np.array([1, 2, 3])
np_array.dtype

dtype('int64')

In [15]:
np_array = np.array([1., 2., 3.])
np_array.dtype

dtype('float64')

In [16]:
np_array = np.array([0, 1, 2, 3])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.LongTensor'

In [17]:
np_array = np.array([1., 2., 3.])
torch_array = torch.from_numpy(np_array)
torch_array.type()

'torch.DoubleTensor'

In [8]:
np_array = np.array([1, 2, 3], dtype=float)
np_array.dtype

dtype('float64')

In [16]:
np_array = np.array([1, 2, 3], dtype=float)
torch_array = torch.from_numpy(np_array)
print(torch_array.dtype)
print(torch_array.type())

torch.float64
torch.DoubleTensor


In [17]:
np_array = np.array([1, 2, 3], dtype='int64')
torch_array = torch.from_numpy(np_array)
print(torch_array.dtype)
print(torch_array.type())

torch.int64
torch.LongTensor


In [14]:
#dtypeは型そのものを返す
type(torch_array.dtype)

torch.dtype

In [15]:
#type()は文字列が返ってくる
type(torch_array.type())

str

## テンソル形状をチェックする

In [18]:
xf_numpy = np.ndarray([2, 3], dtype='float32')
print(xf_numpy)
print(xf_numpy.shape)

[[0.    1.875 0.   ]
 [2.    0.    2.125]]
(2, 3)


In [19]:
import torch
xf_torch = torch.FloatTensor(2, 3)
print(xf_torch)
print(xf_torch.size())

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
torch.Size([2, 3])
