In [1]:
import torch
import torch.utils.data

#Tensorからのデータセットの作成

In [7]:
x1 = torch.rand(400, 3)
y1 = torch.rand(400, 1)
dataset1 = torch.utils.data.TensorDataset(x1, y1)   # x1とy1からデータセット1を作成

len(dataset1)   # データセット1のデータ数

400

In [8]:
dataset1[0]     # データセット1の最初の行の内容

(tensor([0.0121, 0.9901, 0.9089]), tensor([0.3177]))

#データセットの結合

In [9]:
x2 = torch.rand(600, 3)
y2 = torch.rand(600, 1)
dataset2 = torch.utils.data.TensorDataset(x2, y2)   # x2とy2からデータセット2を作成

len(dataset2)   # データセット2のデータ数

600

In [10]:
dataset3 = torch.utils.data.ConcatDataset([dataset1, dataset2])     # データセット1とデータセット2を結合してデータセット3を作成

len(dataset3)   # データセット3のデータ数

1000

#データセットの分割

In [11]:
indices4 = [i for i in range(0, 700)]
indices5 = [i for i in range(700, 1000)]
dataset4 = torch.utils.data.Subset(dataset3, indices=indices4)  # データセット3の0~699行からデータセット４を作成
dataset5 = torch.utils.data.Subset(dataset3, indices=indices5)  # データセット3の700~999行からデータセット5を作成

len(dataset4)   # データセット4のデータ数

700

In [12]:
len(dataset5)   # データセット5のデータ数

300

In [13]:
dataset4[0]     # データセット4の最初の行の内容（＝データセット1の最初の行の内容）

(tensor([0.0121, 0.9901, 0.9089]), tensor([0.3177]))

In [14]:
dataset5[0]     # データセット5の最初の行の内容

(tensor([0.3770, 0.6534, 0.1723]), tensor([0.3817]))

#データセットのランダム分割（重複なし）

In [16]:
# データセット3からランダムに700行と300行のデータセットを作成
dataset6, dataset7 = torch.utils.data.random_split(dataset3, [700, 300])

len(dataset6)   # データセット6のデータ数

700

In [17]:
len(dataset7)   # データセット7のデータ数

300

In [18]:
dataset6[0]     # データセット6の最初の行の内容

(tensor([0.2703, 0.4003, 0.1655]), tensor([0.0758]))

In [19]:
dataset7[0]     # データセット7の最初の行の内容

(tensor([0.5379, 0.9860, 0.6402]), tensor([0.5501]))

#データローダー

In [20]:
epoch_size = 5      # エポックサイズの設定
batch_size = 3      # バッチサイズの設定
num_workers = 2     # データ読み込みに使用するサブプロセス数の設定

In [21]:
# データセット3を8:2でトレーニングデータセットとバリデーションデータセットに分割
train_set, valid_set = torch.utils.data.random_split(dataset3, [800, 200])

len(train_set)  # トレーニングデータセットのデータ数

800

In [22]:
len(valid_set)  # バリデーションデータセットのデータ数

200

In [24]:
# トレーニングデータセットのデータローダー（シャッフルON）
train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True, num_workers=num_workers)

# バリデーションデータセットのデータローダー（シャッフルOFF）
valid_loader = torch.utils.data.DataLoader(valid_set, batch_size=batch_size, shuffle=False, num_workers=num_workers)

for epoch in range(epoch_size):     # 学習ループ
    print('########')
    print('epoch:', epoch)
    print('########')

    for itr, data in enumerate(train_loader):   # トレーニングのループ
        print('training loop iteration:', itr)
        print(data)     # シャッフルONなのでエポックごとに異なる
        if itr >= 2:
            break
    print()

    for itr, data in enumerate(valid_loader):   # バリデーションのループ
        print('validation loop iteration:', itr)
        print(data)     # シャッフルOFFなのでエポックが変わっても同一
        if itr >= 2:
            break
    print()

########
epoch: 0
########


training loop iteration: 0
[tensor([[0.1969, 0.7810, 0.0705],
        [0.9704, 0.7199, 0.1348],
        [0.5096, 0.1675, 0.4872]]), tensor([[0.7093],
        [0.9843],
        [0.0582]])]
training loop iteration: 1
[tensor([[0.4182, 0.0102, 0.8858],
        [0.3169, 0.8320, 0.3488],
        [0.1726, 0.1487, 0.2476]]), tensor([[0.5464],
        [0.4406],
        [0.6874]])]
training loop iteration: 2
[tensor([[0.1649, 0.8776, 0.9455],
        [0.5622, 0.1700, 0.8686],
        [0.6193, 0.3062, 0.3511]]), tensor([[0.7984],
        [0.6096],
        [0.9278]])]



validation loop iteration: 0
[tensor([[0.8678, 0.6692, 0.7742],
        [0.6371, 0.1026, 0.2763],
        [0.8830, 0.0627, 0.6976]]), tensor([[0.0817],
        [0.2908],
        [0.6758]])]
validation loop iteration: 1
[tensor([[0.7379, 0.2987, 0.1475],
        [0.4695, 0.0018, 0.5387],
        [0.4746, 0.5025, 0.8335]]), tensor([[0.5897],
        [0.1859],
        [0.6020]])]
validation loop iteration: 2
[tensor([[0.6407, 0.0993, 0.2433],
        [0.9272, 0.9445, 0.1853],
        [0.9318, 0.7057, 0.7579]]), tensor([[0.2345],
        [0.2901],
        [0.6494]])]

########
epoch: 1
########


training loop iteration: 0
[tensor([[0.3303, 0.1698, 0.7258],
        [0.9608, 0.4488, 0.1188],
        [0.6757, 0.7736, 0.7145]]), tensor([[0.6004],
        [0.6274],
        [0.5815]])]
training loop iteration: 1
[tensor([[0.0452, 0.9374, 0.1921],
        [0.8132, 0.4905, 0.0013],
        [0.9806, 0.5789, 0.4964]]), tensor([[0.2065],
        [0.6103],
        [0.1807]])]
training loop iteration: 2
[tensor([[0.9075, 0.6534, 0.8947],
        [0.2553, 0.7156, 0.4117],
        [0.3778, 0.5835, 0.4972]]), tensor([[0.8572],
        [0.7496],
        [0.0353]])]



validation loop iteration: 0
[tensor([[0.8678, 0.6692, 0.7742],
        [0.6371, 0.1026, 0.2763],
        [0.8830, 0.0627, 0.6976]]), tensor([[0.0817],
        [0.2908],
        [0.6758]])]
validation loop iteration: 1
[tensor([[0.7379, 0.2987, 0.1475],
        [0.4695, 0.0018, 0.5387],
        [0.4746, 0.5025, 0.8335]]), tensor([[0.5897],
        [0.1859],
        [0.6020]])]
validation loop iteration: 2
[tensor([[0.6407, 0.0993, 0.2433],
        [0.9272, 0.9445, 0.1853],
        [0.9318, 0.7057, 0.7579]]), tensor([[0.2345],
        [0.2901],
        [0.6494]])]

########
epoch: 2
########


training loop iteration: 0
[tensor([[0.9055, 0.4033, 0.0192],
        [0.9920, 0.6897, 0.4617],
        [0.0464, 0.3264, 0.6852]]), tensor([[0.3786],
        [0.5298],
        [0.4584]])]
training loop iteration: 1
[tensor([[0.7934, 0.4755, 0.5183],
        [0.0075, 0.4875, 0.0383],
        [0.6240, 0.3376, 0.2103]]), tensor([[0.1064],
        [0.3516],
        [0.6366]])]
training loop iteration: 2
[tensor([[0.8595, 0.9278, 0.9775],
        [0.1380, 0.3967, 0.5815],
        [0.0890, 0.0371, 0.8678]]), tensor([[0.1333],
        [0.2560],
        [0.3765]])]



validation loop iteration: 0
[tensor([[0.8678, 0.6692, 0.7742],
        [0.6371, 0.1026, 0.2763],
        [0.8830, 0.0627, 0.6976]]), tensor([[0.0817],
        [0.2908],
        [0.6758]])]
validation loop iteration: 1
[tensor([[0.7379, 0.2987, 0.1475],
        [0.4695, 0.0018, 0.5387],
        [0.4746, 0.5025, 0.8335]]), tensor([[0.5897],
        [0.1859],
        [0.6020]])]
validation loop iteration: 2
[tensor([[0.6407, 0.0993, 0.2433],
        [0.9272, 0.9445, 0.1853],
        [0.9318, 0.7057, 0.7579]]), tensor([[0.2345],
        [0.2901],
        [0.6494]])]

########
epoch: 3
########


training loop iteration: 0
[tensor([[0.1677, 0.3746, 0.9544],
        [0.6232, 0.2552, 0.8245],
        [0.6610, 0.4539, 0.4255]]), tensor([[0.1919],
        [0.3966],
        [0.4432]])]
training loop iteration: 1
[tensor([[0.7062, 0.7595, 0.8360],
        [0.1615, 0.0979, 0.3788],
        [0.3457, 0.2451, 0.8684]]), tensor([[0.5175],
        [0.8472],
        [0.2703]])]
training loop iteration: 2
[tensor([[0.6335, 0.2168, 0.6544],
        [0.5880, 0.6971, 0.9894],
        [0.1649, 0.8776, 0.9455]]), tensor([[0.1952],
        [0.9936],
        [0.7984]])]



validation loop iteration: 0
[tensor([[0.8678, 0.6692, 0.7742],
        [0.6371, 0.1026, 0.2763],
        [0.8830, 0.0627, 0.6976]]), tensor([[0.0817],
        [0.2908],
        [0.6758]])]
validation loop iteration: 1
[tensor([[0.7379, 0.2987, 0.1475],
        [0.4695, 0.0018, 0.5387],
        [0.4746, 0.5025, 0.8335]]), tensor([[0.5897],
        [0.1859],
        [0.6020]])]
validation loop iteration: 2
[tensor([[0.6407, 0.0993, 0.2433],
        [0.9272, 0.9445, 0.1853],
        [0.9318, 0.7057, 0.7579]]), tensor([[0.2345],
        [0.2901],
        [0.6494]])]

########
epoch: 4
########


training loop iteration: 0
[tensor([[0.1752, 0.8813, 0.0413],
        [0.1629, 0.1804, 0.7786],
        [0.9595, 0.7946, 0.1695]]), tensor([[0.8211],
        [0.6245],
        [0.8714]])]
training loop iteration: 1
[tensor([[0.3303, 0.1698, 0.7258],
        [0.6826, 0.4501, 0.6100],
        [0.4809, 0.7765, 0.8901]]), tensor([[0.6004],
        [0.1192],
        [0.3797]])]
training loop iteration: 2
[tensor([[0.9678, 0.0594, 0.8241],
        [0.6858, 0.3087, 0.7685],
        [0.3958, 0.2562, 0.9763]]), tensor([[0.1304],
        [0.2343],
        [0.2368]])]



validation loop iteration: 0
[tensor([[0.8678, 0.6692, 0.7742],
        [0.6371, 0.1026, 0.2763],
        [0.8830, 0.0627, 0.6976]]), tensor([[0.0817],
        [0.2908],
        [0.6758]])]
validation loop iteration: 1
[tensor([[0.7379, 0.2987, 0.1475],
        [0.4695, 0.0018, 0.5387],
        [0.4746, 0.5025, 0.8335]]), tensor([[0.5897],
        [0.1859],
        [0.6020]])]
validation loop iteration: 2
[tensor([[0.6407, 0.0993, 0.2433],
        [0.9272, 0.9445, 0.1853],
        [0.9318, 0.7057, 0.7579]]), tensor([[0.2345],
        [0.2901],
        [0.6494]])]

